[package]
authors = ["BoudBoud47 <mehdi.boudart@gmail.com>"]
edition = "2018"
name = "search-algorithm"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
